on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy website to server
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and deploy
        uses: jenshaase/deploy-zola-via-lftp-action@main
        with:
          ftp_host: ${{ secrets.ftp_host }}
          ftp_username: ${{ secrets.ftp_username }}
          ftp_password: ${{ secrets.ftp_password }}
          remote_target_dir: ${{ secrets.ftp_remote_target_dir }}
